### ISSUE TITLE
Use envService in factory section

### ISSUE THREAD

**Issue by jlethuau** [juanpablob/angular-environment#11]
Hi and first of all, thanks for this useful module.

I would like to use environment variables in a factory section since I need these values to instantiate another module: https://github.com/btford/angular-socket-io

My code look like this and I have to comment/uncomment some lines when I migrate from one env to anoher...

``` php
myApp.factory('mySocket', function (socketFactory) {
    // TODO: choose proper URL : need access to 'envService' here...
    //var myIoSocket = io.connect('http://127.0.0.1:12345'); // local
    var myIoSocket = io.connect('http://XXX.XXX.XXX.XXX:9000'); // production
    return socketFactory({
        ioSocket: myIoSocket
    });
});
```

Any suggestion on the proper way to do that?

I think that's not a very different question than this one: #10 

Thanks in advance

**Comment by juanpablob** [comment]
Hello @jlethuau, thank you for asking and sorry for the delay! I think the right way to achieve that is by doing this:

First of all, define the socket address for each environment, as seen in the demo:

``` js
myapp.config(function(envServiceProvider) {
    // set the domains and variables for each environment
    envServiceProvider.config({
        domains: {
            development: ['localhost', 'dev.local'],
            production: ['yourdomain.com', 'alternativedomain.com']
            // anotherStage: []
        },
        vars: {
            development: {
                socketUrl: 'http://127.0.0.1:12345'
                // antoherCustomVar: ''
            },
            production: {
                socketUrl: 'http://200.27.42.12:9000'
                // antoherCustomVar: ''
            }
        }
    });

    // run the environment check, so the comprobation is made
    // before controllers and services are built
    envServiceProvider.check();
});
```

From now, you can inject `envService` into a factory or service and reference the socketUrl via `read` method:

``` js
myApp.factory('mySocket', function (socketFactory) {
        var myIoSocket = io.connect(envService.read('socketUrl')); //defined during config
        // so, myIoSocket will return the socketUrl variable depending on which environment you are

        return socketFactory({
                ioSocket: myIoSocket
        });
});
```

Hope it helps. Anyways, for the next time I suggest you to read the documentation, since this example is present in the `README.md` and also in the demo of this app.

Cheers!

**Comment by jlethuau** [comment]
Hi and thanks for this answer.
Maybe I wasn't clear in my question but I had already tried that.

With quite the same code, I have this error : `angular.js:13424 ReferenceError: envService is not defined`

That's why I thought it was impossible and then I decided to ask you a question.

Do you know what's wrong so I cannot access the `envService`object in this factory ?

**Comment by jlethuau** [comment]
I've finally found that I had to pass an extra parameter to the factory:

``` php
myApp.factory('mySocket', function (socketFactory, envService) {
    var myIoSocket = io.connect(envService.read('socketUrl')); //defined during config
    // ...
});
```

Thanks for your help!
