### ISSUE TITLE
Causing errors in Jasmine test

### ISSUE THREAD

**Issue by alib192** [juanpablob/angular-environment#14]
Hi, 

I have started using your library and it works perfectly in the application, however it causes the error:

undefined is not an object (evaluating 'this.data.vars[this.get()]') in .../bower_components/angular-environment/src/angular-environment.js (line 59)

when called in a unit test.

Thanks

**Comment by faceleg** [comment]
Inside a test, console log `window.location.host` and add that domain as one of your environment domains in the angular-environment config.
