### ISSUE TITLE
Configuring protocols...

### ISSUE THREAD

**Issue by ESPlanner** [juanpablob/angular-environment#15]
It would be nice if you're running different environments using different protocols (http vs https) for url/uri "things" to automatically get the current protocol attached when read.  For example:

Anything of the form: '//...' would get the window.location.protocol attached

or

Anything named: ...Url or ... Uri would get same thing.

of the two, I prefer the first since naming habits are more or less the property of an individual but the form of a uri/url is defined externally.

**Comment by juanpablob** [comment]
You're right. I'll introduce something to add protocol prefixes. Thanks for your input.
