### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by faceleg** [juanpablob/angular-environment#16]
It'd be great to see some unit tests, other than that thanks for making this!

**Comment by FullStackForger** [comment]
Hey @faceleg @juanpablob!
Is anyone planning to tackle unit testing at some point or is it something you need help with?

Very neat plugin btw. Loving it!

**Comment by juanpablob** [comment]
I just released a new version with some improvements. During next weeks I'll look into the behavior of this plugin into a unit testing. Cheers!

**Comment by juanpablob** [comment]
@fullstackforger @faceleg The unit testing for this plugin was just added by @rars (thank you!!), it's on the master branch, check it out! In the next days I'll release a new version of the plugin including the unit testing ;)
