### ISSUE TITLE
Request: Support a 'defaults' set in config vars

### ISSUE THREAD

**Issue by jaybayley** [juanpablob/angular-environment#18]
Hi there,

Thank you for the great plugin. One useful feature i'd like to see is the ability to set defaults in the vars object, that get used if not defined in a specific environment - something like this:

```
# coffeescript

envServiceProvider.config
    domains:
      development: [
        'localhost'
      ]
      staging: [
        'staging.acme.com'
      ]
      production: [
        'acme.com'
      ]
    vars:
      defaults:
        s3Bucket: 'abcdefg123456789'
      development:
        apiUrl: 'https://localhost/api/url'
      staging:
        apiUrl: 'https://staging.acme.com/api/url'
      production:
        apiUrl: 'https://www.acme.com/api/url'
        s3Bucket: 'hijklmn987654321'

envServiceProvider.check()
```

With the above config, I would expect `envService.read('s3Bucket')` to return `hijklmn987654321` for `production`, and `abcdefg123456789` for `development` and `staging`.

This would be a small but useful addition when dealing with large sets of environments/variables.

Thanks again!

**Comment by kgoedert** [comment]
+1

**Comment by edgaralves** [comment]
+1

**Comment by juanpablob** [comment]
@jaybayley @kgoedert @edgaralves thank you guys for your feedback, there's no doubt that it could be a great feature, I'll do my best to include it in the next release. Thank you again ;)

Cheers!

**Comment by juanpablob** [comment]
@jaybayley @kgoedert @edgaralves Hi guys! The new version has just released, including default vars ;)

**Comment by juanpablob** [comment]
I just released a last version because I forgot to add the compiled scripts in the previous release. Sorry about that. Now you can update to latest.
