### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by stevie-p** [juanpablob/angular-environment#19]
Hi

Looking at the source code, I think that your `check()` may not work for subdomains as you intend:

If

```
var domain = "example.com"
var location = "https://subdomain.example.com";
var result = location.match(new RegExp("^http(s)?:\/\/" + domain);  // null = no match
```

May I suggest something along the lines of:

```
var regex = new RegExp(domain + '$');  // $ tests for 'domain' at the end of the string
var result = regex.test(window.location.hostname);
```

I could submit a Pull Request - but I'm new to this stuff - it would be my first PR!
:-)

**Comment by juanpablob** [comment]
Thank you @stevie-p, I'll look into this, since I'm working for a new release.

Cheers!

**Comment by juanpablob** [comment]
@stevie-p Tomorrow sunday I will release a new version that allows to use subdomains and also * as wildcards for domains, i.e. `subd.*.com` or `*.dom.com`. Cheers!

**Comment by juanpablob** [comment]
The version has just released. Enjoy.

**Comment by juanpablob** [comment]
I just released a last version because I forgot to add the compiled scripts in the previous release. Sorry about that. Now you can update to latest.
