### ISSUE TITLE
How to use it with routes?

### ISSUE THREAD

**Issue by ssuryawa** [juanpablob/angular-environment#21]
Hi,

Thanks for such a great plug-in. I want to use the 'envService' in routes like below:

Any suggestion on how to use this?

var routeDetails = function ($routeProvider,$locationProvider,envService){
       var SERVER_ENDPOINT = envService.read('staticUrl');

```
$routeProvider.
when('/', {
    templateUrl: SERVER_ENDPOINT + '/partials/home.html',
    controller: 'Controller',
}). when('/guides', {
    templateUrl: SERVER_ENDPOINT + '/partials/guides.html',
    controller: 'GuidesController',
}
```

}

Thanks,
Shailendra

**Comment by kbzowski** [comment]
+1

**Comment by juanpablob** [comment]
Hi there! As @ssuryawa said above, you can set `var server_endpoint = envService.read('staticUrl');` and then use it to call the template url, i.e: `templateUrl: server_endpoint + '/partials/home.html'` so, there you are!
