### ISSUE TITLE
Syntax error in "full example"

### ISSUE THREAD

**Issue by geraldleung** [juanpablob/angular-environment#24]
Upon copying and pasting the example into my app, I got an angularJS error: "_Failed to instantiate module ..."__

I spotted a syntax error where the closing brace for the "test" element did not have an ending  comma after the closing brace.  Please update the documentation with working syntax.

Thanks for contributing this library!

**Comment by juanpablob** [comment]
@geraldleung Hey mate, thank you for notify the error! I just updated the readme, probably should be a great create a new tag based on last commit with this fix.

Cheers!
