### ISSUE TITLE
check() not matching correctly

### ISSUE THREAD

**Issue by juampick** [juanpablob/angular-environment#25]
Hi.. @juanpablob I think we are currently having this issue on the latest `1.0.7` version.
This is related with #22 #23 #19 I think so.
It's not matching correctly when using subdomains like:

dev: 'dapp.test.com',
test: 'tapp.test.com',
production: 'app.test.com'.
It's always setting as the production to be the environment, incorrectly.

I think the issue is on the check() method and this commit:
3cd588e

Could you please take a look?

**Comment by juampick** [comment]
Rollbacked to `1.0.4` and working awesome. So the issue is with the later versions. Thanks!

**Comment by juanpablob** [comment]
@juampick hey, thank you for notify the bug. Can you please give me in detail your environments? So I can simulate exactly the same to see what's happening and make a better debugging.
Thank you!

**Comment by juanpablob** [comment]
@juampick I just simulated the environments you wrote above as example and you were right, there was a problem during domain matching in `check()`. I wrote a fix and made some enhancements, please try it :) The new version is out.

Cheers!

**Comment by portalsaluddoc24** [comment]
Nice version `1.0.8` working like a charm! thanks!
