### ISSUE TITLE
console.log(v.domain);

### ISSUE THREAD

**Issue by AlexMcConnell** [juanpablob/angular-environment#32]
Having this spam between each of my unit tests is incredibly annoying. Is there any way for me to stop it from happening?

**Comment by hirashuriken** [comment]
agree, could you remove it or make customizable?

**Comment by juanpablob** [comment]
Hey guys! Sorry, I've been kinda busy… I'll try to sort out a solution for this in the next few days, otherwise I will remove the `console.log` from the source.
Cheers!

**Comment by AlexMcConnell** [comment]
Any update on this? I was about to fork this project and point to that instead, but I'd rather not.

**Comment by kennydifiore** [comment]
????? Can you remove the console log?

**Comment by juanpablob** [comment]
It's merged now!
