### ISSUE TITLE
`Error: No pending request to flush !` with $http

### ISSUE THREAD

**Issue by ivanbreet** [juanpablob/angular-environment#6]
Hi,

First of all, this is a nifty little module.

The moment when I added this module it started to break my unit test. Basically any place where I use an environmental variable in an $http call path, it breaks with the following error:
`Error: No pending request to flush !`

**Comment by juanpablob** [comment]
Hello @ivanbreet, sorry for the delay. I will look into this. By the moment you're the only who's having this issue but I'll test something and I'll let you know. Thanks!

Cheers!

**Comment by faceleg** [comment]
@ivanbreet `console.log` your `$http` url to verify it is as you expect, it may be that phantomjs is serving your files from a domain that is not set in your environment domains object.
