### ISSUE TITLE
`npm install` does not pull down index.js

### ISSUE THREAD

**Issue by terrawheat** [juanpablob/angular-environment#9]
I think that after merging in PR #4 an NPM publish is required.

Currently when I install it is downloaded without.

```
foo$ npm install angular-environment
angular-environment@1.0.3 node_modules\angular-environment
foo$ ls node_modules/angular-environment/
bower.json  bower_components/  demo/  dist/  gulpfile.js  LICENSE  package.json  README.md  src/
```

**Comment by DaleLJefferson** [comment]
Any change we can publish a new version that includes PH #4 

If anyone else if having the same issue this is the current workaround.

```
"angular-environment": "git+https://github.com/juanpablob/angular-environment.git#7ce0f2cbe4dd35fa9a7133cf84e373079de44c69",
```

**Comment by danielcruzks** [comment]
There is not index.js and an entry point in the packages.json file. Any thoughts?

**Comment by terrawheat** [comment]
The latest `master` does have these, but it doesn't look like these changes have been versioned and pushed to NPM :/

Thats what this issue is open for

**Comment by juanpablob** [comment]
Hello everyone! This issue was fixed on the latest release: _v.1.0.4_ — Thanks!
